services:
  db:
    image: postgres:18.3-alpine3.23
    environment:
      - POSTGRES_DB=pluton_media_db_dev
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pluton-media-db-data:/var/lib/postgresql/data

volumes:
  pluton-media-db-data: